package com.example.sitiopro.tarefas.entity;

public enum TipoEventoOperacional {
    TAREFA_CRIADA,
    TAREFA_EDITADA,
    TAREFA_INICIADA,
    TAREFA_CONCLUIDA,
    TAREFA_CANCELADA,
    RECORRENCIA_GERADA,
    RECORRENCIA_DESATIVADA,
    ALERTA_DETECTADO,
    ALERTA_ATUALIZADO,
    ALERTA_RECONHECIDO,
    ALERTA_RESOLVIDO,
    ALERTA_TAREFA_CRIADA
}
